version: '3.8'
services:
  backend:
    build: ./back
    depends_on:
      - mongodb
    networks:
      - todo-app
  frontend:
    build: ./front
    container_name: todo-app-front
    hostname: todo-app-front
    depends_on:
      - backend
    networks:
      - todo-app
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: no
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: aws123
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./back/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todo-app

networks:
  todo-app:
